version: '3.9'
services:
  database:
    image: 'postgres:11.15-alpine'
    container_name: 'database-bacon'
    restart: 'always'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bacon
    volumes:
      - bacon-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build:
      context: packages/server
      dockerfile: Dockerfile
    container_name: backend-bacon
    # command: sh -c "npm install && npm run start:dev"
    depends_on:
      - database
    volumes:
      - ./packages/server/:/app
      - node-modules:/app/node_modules
      # - dist:/app/dist
    ports:
      - 4000:4000

    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URL=mongodb://database-bacon:27017/bacon
  cache:
    image: redis:6.2-alpine
    container_name: bacon-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  bacon-postgres:
  node-modules:
  dist:
  cache:
    driver: local